name: Expo Android Build

on:
  push:
    branches:
      - production
    tags:
      - 'v*'

env:
  EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Build Android APK
        run: eas build --platform android --non-interactive --profile production

      - name: Download build artifact
        run: |
          # Get the latest build ID and download the APK
          BUILD_ID=$(eas build:list --platform android --status finished --limit 1 --json | jq -r '.[0].id')
          eas build:download --platform android --output hercules-app.apk --id $BUILD_ID

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: hercules-app
          path: hercules-app.apk
          retention-days: 30
